host: test.salesforce.com
client_id: 3MVG9GiqKapCZBwGKWN18VcBTA5d82sFCh7vEQx5F1GRPo5guUOp1SJrDNereyBomRnYHv5oE7a1VJuu8fBdC
client_secret: 1042066715413818107
username: orgadmin@ucsf.concierge.edu.npidev
password: Concierge32757yR67urQJCWHdg4HdsGHI07Zy
debugging: true