host: login.salesforce.com
client_id: 3MVG9QDx8IX8nP5QL6nLuLAMcTCSWgq4tUAdKxjxtxVx8srPQ2sGc9BxogVht4XM1wblfmbu0eG5gynnXOmhe
client_secret: 2958068219577184555
username: dev1@surveysdev.com
password: surveys1234
debugging: true